# AutoencoderKL (diffusers) wrapped for EulerAudioBackbone

model:
  autoencoder:
    return_latent: false
    pre_transform:
      type: power_norm     # none | log_mag | power_norm
      apply_target: true
      apply_inverse: true
      config:
        eps: 1.0e-8
        alpha: 0.65
        beta: 0.35

  encoder:
    _target_: ar_spectra.models.autoencoder_kl.HFAutoencoderKLEncoder
    # input_size MUST match data.model_channels (complex-as-channels stereo => 4)
    input_size: 4
    is_complex: false
    latent_channels: 4
    down_block_types: ["DownEncoderBlock2D", "DownEncoderBlock2D", "DownEncoderBlock2D", "DownEncoderBlock2D"]
    block_out_channels: [128, 128, 256, 256]
    layers_per_block: 2
    act_fn: silu
    norm_num_groups: 32
    mid_block_add_attention: true
    scaling_factor: 0.18215

  decoder:
    _target_: ar_spectra.models.autoencoder_kl.HFAutoencoderKLDecoder
    # channels MUST match data.model_channels (complex-as-channels stereo => 4)
    channels: 4
    is_complex: false
    latent_channels: 4
    up_block_types: ["UpDecoderBlock2D", "UpDecoderBlock2D", "UpDecoderBlock2D", "UpDecoderBlock2D"]
    block_out_channels: [128, 128, 256, 256]
    layers_per_block: 2
    act_fn: silu
    norm_num_groups: 32
    mid_block_add_attention: true
    use_post_quant_conv: true
    scaling_factor: 0.18215

  bottleneck:
    _target_: ar_spectra.models.bottlenecks.VAEBottleneck
