# Model configuration - Hydra instantiate API (Real SEANet)
# Use _target_ for automatic instantiation via hydra.utils.instantiate

model:
  autoencoder:
    return_latent: false
    pre_transform:
      type: none     # none | log_mag | power_norm
      apply_target: true
      apply_inverse: true
      config:
        eps: 1.0e-8
        alpha: 0.65
        beta: 0.35

  encoder:
    _target_: ar_spectra.models.autoencoders.SeaNET_AE.SEANetEncoder2d
    # input_size MUST match data.model_channels
    input_size: 4
    dimension: 256
    n_filters: 8
    n_residual_layers: 1
    ratios: [[4,2],[1,2],[4,2]]
    activation: ELU
    norm: weight_norm
    norm_params: {num_groups: 1}
    causal: false
    latent_fbins: 64
    dilation_base: 2
    seq_model: none
    is_complex: false

  decoder:
    _target_: ar_spectra.models.autoencoders.SeaNET_AE.SEANetDecoder2d
    # channels MUST match data.model_channels
    channels: 4
    input_size: 128
    n_filters: 8
    n_residual_layers: 1
    ratios: [[4,2],[1,2],[4,2]]
    activation: ELU
    norm: weight_norm
    norm_params: {num_groups: 1}
    causal: false
    latent_fbins: 64
    dilation_base: 2
    seq_model: none
    is_complex: false

  bottleneck:
    _target_: ar_spectra.models.bottlenecks.VAEBottleneck
